name: Example workflow for Node using Snyk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
         cd T-WEB-700-COT_3-main/
         cd api
         npm install dotenv
         npm audit
         npm audit fix
         npm run dev
         cd ../front-office/money-count
         npm install dotenv
         npm audit
         npm audit fix
         npm run dev
         
  security:  
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - uses: snyk/actions/node@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
        command: code test
